### ISSUE TITLE
이벤트 알림 작업

### ISSUE THREAD

**Issue by sunyou10** [9oormthon-univ/2024_DANPOONG_TEAM_20_BE#14]
## 🚀 Description

- SSE(Server-Sent-Events)로 실시간 이벤트 알림 구현

## ✅ TODO

- [ ]  알림 엔티티 생성
- [ ] Sse Emitter 연결하는 컨트롤러 구현
- [ ] 게시글 댓글 알림 전송 기능 구현
- [ ] 새로운 쪽지 알림 전송 기능 구현
- [ ] Streak 마감 임박 알림 전송 기능 구현
